### ISSUE TITLE
Create draft sdds.

### ISSUE THREAD

**Issue by mashua** [librespacefoundation/upsat-org#25]

**Comment by mashua** [comment]
SDD creation for various subsystems (software design documents for subsystems communication (internal/external)

**Comment by mashua** [comment]
drafts are here:
1) https://docs.google.com/document/d/1T9UHv2GNEKDRTun88d5X0XlIR8mVypFvf-zPkitAtEI/edit?ts=56c45155

**Comment by ppapadeas** [comment]
open for viewing public for all.
