### ISSUE TITLE
Cut Berillium copper for antennas

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-org#26]
Dimensions should be uploaded here.

**Comment by manostheodoridis** [comment]
we should have them in different lengths so that we can explore all the options that involve placement and matching


UHF lengths in mm:  165, 171, 180, 195, 200
VHF lengths in mm:   55, 60, 64, 65
         width   in mm:  3

**Comment by ppapadeas** [comment]
VHF lengths in mm: 550, 600, 640, 650
