### ISSUE TITLE
Order SunSensor Connector

### ISSUE THREAD

**Issue by ppapadeas** [librespacefoundation/upsat-org#36]

**Comment by ppapadeas** [comment]
http://www.omnetics.com/products/bilobe/pdffiles/A28000-009.pdf

**Comment by AndreasAmp** [comment]
payment confirmation. ready for shipment

**Comment by AndreasAmp** [comment]
DHL #3437486076 for tracking

**Comment by AndreasAmp** [comment]
Delivered @AML
